name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.x
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
    - run: npm install
    - run: cat package.json
    - run: node --version
    - run: ls -l test/
    - run: ls -l lib/
    - run: npm run build
